# Generated by Django 3.2.8 on 2021-11-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacetime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Honorarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('ad_group', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.TextField()),
                ('advisories', models.TextField()),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('booking_start', models.DateField()),
                ('booking_end', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('eventbrite_link', models.CharField(max_length=255)),
                ('meetup_link', models.CharField(max_length=255)),
                ('free_spaces', models.IntegerField()),
                ('paid_spaces', models.IntegerField()),
                ('members_only', models.BooleanField()),
                ('age_restriction', models.IntegerField(default=0, max_length=3)),
                ('attendeees_require_approval', models.BooleanField(default=False)),
                ('attendee_cancellation_end', models.DateTimeField()),
                ('extend_registration', models.IntegerField(default=0, max_length=11)),
                ('class_number', models.IntegerField(default=0, max_length=1)),
                ('sponsored', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('cancel_notification', models.BooleanField(default=True)),
                ('reminder_notification', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contact_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacetime.contact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_created_contact_id', to='spacetime.contact')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_rejected_contact_id', to='spacetime.contact')),
                ('room_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='spacetime.room')),
            ],
        ),
    ]
